# Generated by Django 6.1 on 2026-09-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(choices=[('Pocket Money', 'Pocket Money'), ('Scholarship', 'Scholarship'), ('Freelance Income', 'Freelance Income')], max_length=100),
        ),
    ]
