# Generated by Django 6.1 on 2026-09-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_income_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Shopping', 'Shopping'), ('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Miscellaneous', 'Miscellaneous')], default='Food', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budget',
            name='period',
            field=models.CharField(default='Monthly', max_length=50),
        ),
    ]
